LLM:
  engine: "generation-davinci-003"
  max_tokens: 1024
  temperature: 0.1
  top_p: 0.5
  frequency_penalty: 0
  presence_penalty: 0
  best_of: 1
  stop: None
Prompt:
  AnonymizeAuthor:
    Context: >
      Anonymize the author name everywhere in the following email, but apart from this leave the email as it is.
  AnonymizeRecipent:
    Context: >
      Anonymize the recipient of the following email everywhere, but apart from this leave the email  as it is.
